### ISSUE TITLE
ready for deploy

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/test#10]
@zulipbot claim
@zulipbot label "bug" "not a label"

**Comment by zulipbot-test** [comment]
**Error:** Label "not a label" does not exist and was thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot label "buggy" "not a label"

**Comment by zulipbot-test** [comment]
**Error:** Labels "buggy", "not a label" do not exist and were thus not added to this issue.

**Comment by synicalsyntax** [comment]
Success!
