### ISSUE TITLE
Ready for deploy

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/test#13]
@zulipbot claim

**Comment by zulipbot-test** [comment]
Congratulations @synicalsyntax, you've successfully claimed your first issue!

Please review our [code contribution guidelines](http://zulip.readthedocs.io/en/latest/index.html#code-docs) and sign the [Dropbox Contributor License Agreement](https://opensource.dropbox.com/cla/) before opening any pull requests for any issues that you're working on!

Also, if you haven't done so already, please join us on the [Zulip developer's chat!](https://chat.zulip.org/).

**Note:** Depending on your [notification settings](https://github.com/settings/notifications), you might be automatically watching this repository, which means that you'll get notifications for any new pull requests and issues that are created. If you don't want to receive notifications for this repository, you should unwatch this repository.
