### ISSUE TITLE
zulipbot

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/test#8]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by zulipbot-test** [comment]
**Error:** Labels ""bug"do not exist and were thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by zulipbot-test** [comment]
**Error:** Labels "bug" do not exist and were thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot label "bug"

**Comment by synicalsyntax** [comment]
@zulipbot label "bug" "not"

**Comment by zulipbot-test** [comment]
**Error:** Labels "not" do not exist and were thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot label "bug" "not" "poo"

**Comment by zulipbot-test** [comment]
**Error:** Labels "not", "poo" do not exist and were thus not added to this issue.
