### ISSUE TITLE
zu

### ISSUE THREAD

**Issue by synicalsyntax** [zulipbot-testing/test#9]
@zulipbot claim

**Comment by synicalsyntax** [comment]
@zulipbot label "bug" "not" "poo"

**Comment by zulipbot-test** [comment]
**Error:** Labels ${rejectedLabelsString} do not exist and were thus not added to this issue.

**Comment by synicalsyntax** [comment]
@zulipbot label "poo"

**Comment by zulipbot-test** [comment]
**Error:** Label ${rejectedLabelsString} does not exist and was thus not added to this issue.
